version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:123456PW@postgres:5432/final-challenge-db
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: postgres_container_final_challenge
    environment:
      - POSTGRES_DB=final-challenge-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456PW
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: